name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        env:
          # Bun's WebAssembly JIT intermittently crashes/returns bogus results when
          # compiling the stage1 compiler. Disabling the BBQ/OMG tiers keeps the
          # execution deterministic while remaining fast enough for CI.
          BUN_JSC_useBBQJIT: "0"
          BUN_JSC_useOMGJIT: "0"
        run: bun test
